name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.18'

            - name: Install dependencies
              run: npm install

            - name: Set environment variables
              run: echo ${{ secrets.ANGULAR_ENVIRONMENT }} > src/environments/environment.ts

            - name: Deploy to Firebase Hosting
              run: npm run deploy
